defaults: &defaults
  working_directory: ~/workspace
  machine:
    image: ubuntu-2004:202101-01
  resouce_class: arm.medium

version: 2
jobs:
  publish:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Install prerequisites
          command: |
            sudo apt update
            sudo apt install -y openssl snap curl
            sudo snap install snapcraft
            curl https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-arm64.tar.gz | tar zx
            sudo cp -r node-v16.14.2-linux-arm64/* /usr/local

      - run:
          name: Build snap
          command: |
            npm i
            npm run dist-snap-arm64

      - run:
          name: Decrypt credentials
          command: |
            openssl aes-256-cbc -d \
              -in .circleci/credentials.enc \
              -out credentials \
              -k $SNAPCRAFT_CREDENTIALS_KEY

      - run:
          name: Authenticate snapcraft
          command: snapcraft login --with credentials

      - run:
          name: Push/release snap
          command: snapcraft push dist/*.snap --release stable

workflows:
  version: 2
  commit:
    jobs:
      - publish:
          filters:
            tags:
              only: /^c[0-9]+.[0-9]+.[0-9]+$/