version: 2.1

defaults: &defaults
  working_directory: ~/workspace
  
jobs:
  build-amd64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build snap
          command: |
            npm run dist-snap

      - persist_to_workspace:
          root: ~/workspace
          paths: ['dist/*.snap']

  build-arm64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build snap
          command: |
            npm run dist-snap

      - persist_to_workspace:
          root: ~/workspace
          paths: ['dist/*.snap']

  publish:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout

      - attach_workspace:
          at: ~/workspace

      - run:
          name: Decrypt credentials
          command: |
            openssl aes-256-cbc -d \
              -in .circleci/credentials.enc \
              -out credentials \
              -k $SNAPCRAFT_CREDENTIALS_KEY

      - run:
          name: Authenticate snapcraft
          command: snapcraft login --with credentials

      - run:
          name: Push/release snap
          command: find dist -name "*.snap" | xargs -I {} snapcraft upload {} --release beta

workflows:
  version: 2
  snap:
    jobs:
      - build-amd64:
          filters:
            tags:
              only: /^[vt][0-9]+.[0-9]+.[0-9]+$/
            branches:
              ignore: /.*/
      - build-arm64:
          filters:
            tags:
              only: /^[vt][0-9]+.[0-9]+.[0-9]+$/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - build-amd64
            - build-arm64
          filters:
            tags:
              only: /^[vt][0-9]+.[0-9]+.[0-9]+$/
            branches:
              ignore: /.*/