version: 2.1

defaults: &defaults
  working_directory: ~/workspace
  
jobs:
  build-snap-amd64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build snap
          command: |
            npm run dist-snap

      - persist_to_workspace:
          root: ~/workspace
          paths: ['dist/*.snap']

  build-snap-arm64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build snap
          command: |
            npm run dist-snap

      - persist_to_workspace:
          root: ~/workspace
          paths: ['dist/*.snap']

  publish:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout

      - attach_workspace:
          at: ~/workspace

      - run:
          name: Push/release snap
          command: find dist -name "*.snap" | xargs -I {} snapcraft upload {} --release beta

  build-appImage-arm64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build AppImage
          command: |
            GH_TOKEN=${GH_TOKEN} npm run docker-dist-appImage -- -- -p always --arm64

  test-build-appImage-arm64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build AppImage
          command: |
            npm run docker-dist-appImage

      - store_artifacts:
          path: dist

  build-deb-arm64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build deb
          command: |
            sudo apt update
            sudo apt -y install ruby ruby-dev
            gem install fpm -f
            npm i --ignore-scripts
            GH_TOKEN=${GH_TOKEN} npm run dist-deb -- -p always --arm64

  build-rpm-aarch64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Build rpm
          command: |
            sudo apt update
            sudo apt -y install ruby ruby-dev rpm
            gem install fpm -f
            npm i --ignore-scripts
            GH_TOKEN=${GH_TOKEN} npm run dist-rpm -- -p always --arm64

workflows:
  version: 2
  snap:
    jobs:
      - build-snap-amd64:
          filters:
            tags:
              only: /^[vc][0-9]+.[0-9]+.[0-9]+$/
            branches:
              ignore: /.*/
      - build-snap-arm64:
          filters:
            tags:
              only: /^[vc][0-9]+.[0-9]+.[0-9]+$/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - build-snap-amd64
            - build-snap-arm64
          filters:
            tags:
              only: /^[vc][0-9]+.[0-9]+.[0-9]+$/
            branches:
              ignore: /.*/
  appImage:
    jobs:
      - build-appImage-arm64:
          filters:
            tags:
              only: /^([vc][0-9]+.[0-9]+.[0-9]+|appImage-arm64)$/
            branches:
              ignore: /.*/

  deb:
    jobs:
      - build-deb-arm64:
          filters:
            tags:
              only: /^([vc][0-9]+.[0-9]+.[0-9]+|deb-arm64)$/
            branches:
              ignore: /.*/
  rpm:
    jobs:
      - build-rpm-aarch64:
          filters:
            tags:
              only: /^([vc][0-9]+.[0-9]+.[0-9]+|rpm-aarch64)$/
            branches:
              ignore: /.*/

  test:
    jobs:
      - hold:
          type: approval
      - build-snap-amd64:
          requires:
            - hold
      - build-snap-arm64:
          requires:
            - hold
      - publish:
          requires:
            - hold
            - build-snap-amd64
            - build-snap-arm64
