version: 2.1

defaults: &defaults
  working_directory: ~/workspace
  
jobs:
  build-amd64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout

      - run:
          name: Install prerequisites
          command: |
            curl https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-x64.tar.gz | tar zx
            sudo cp -r node-v16.14.2-linux-x64/* /usr/local

      - run:
          name: Build snap
          command: |
            npm i
            npm run dist-snap

      - persist_to_workspace:
          root: ~/workspace
          paths: ['dist/*.snap']

  build-arm64:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout

      - run:
          name: Install prerequisites
          command: |
            curl https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-arm64.tar.gz | tar zx
            sudo cp -r node-v16.14.2-linux-arm64/* /usr/local

      - run:
          name: Build snap
          command: |
            npm i
            npm run dist-snap-arm64

      - persist_to_workspace:
          root: ~/workspace
          paths: ['dist/*.snap']

  publish:
    <<: *defaults
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout

      - attach_workspace:
          at: ~/workspace

      - run:
          name: Decrypt credentials
          command: |
            openssl aes-256-cbc -d \
              -in .circleci/credentials.enc \
              -out credentials \
              -k $SNAPCRAFT_CREDENTIALS_KEY

      - run:
          name: Authenticate snapcraft
          command: snapcraft login --with credentials

      - run:
          name: Push/release snap
          command: snapcraft push dist/*.snap --release stable

workflows:
  version: 2
  snap:
    jobs:
      - build-amd64:
          filters:
            tags:
              only: /^v[0-9]+.[0-9]+.[0-9]+$/
      - build-arm64:
          filters:
            tags:
              only: /^v[0-9]+.[0-9]+.[0-9]+$/
      - publish:
          requires:
            - build-amd64
            - build-arm64