name: cbetar2
base: core20
confinement: strict
grade: stable
adopt-info: cbetar2

apps:
  cbetar2:
    command: cbetar2/cbetar2 --no-sandbox
    desktop: cbetar2/io.github.mrmyhuang.cbetar2.desktop
    extensions: [gnome-3-38]
    plugs:
    - desktop
    - desktop-legacy
    - wayland
    - browser-support
    - network
    - network-bind
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  cbetar2:
    plugin: nil
    source: .
    parse-info: [buildElectron/io.github.mrmyhuang.cbetar2.metainfo.xml]
    override-build: |
        npm i --ignore-scripts
        npm run build-electron
        npm x -- electron-builder -l dir -c electronBuilderConfigs/snap.json
        electronPackagePath=./dist/linux-unpacked
        cp snap/local/io.github.mrmyhuang.cbetar2.desktop ${electronPackagePath}
        cp -rv ${electronPackagePath} $SNAPCRAFT_PART_INSTALL/cbetar2
    build-snaps:
    - node/16/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4