name: Publish

on:
  push:
    branches:
      - "!*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      target_job:
        description: "Select which job to run"
        required: true
        default: all
        type: choice
        options:
          - all
          - publish-win-x64
          - publish-win-arm64
          - publish-mac-universal
          - publish-appImage-x86_64
          - publish-appImage-arm64
          - publish-deb-amd64
          - publish-deb-arm64
          - publish-rpm-x86_64
          - publish-rpm-aarch64
          - build-snap-amd64
          - build-snap-arm64
          - publish-snap

env:
  DEFAULT_BRANCH: master
  NODE_VERSION: 20
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
  CSC_LINK: ${{ secrets.MAC_CERTS }}
  CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}

jobs:
  publish-win-x64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-win-x64' }}
    runs-on: windows-2025

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup nodejs
        if: ${{ success() }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and publish
        if: ${{ success() }}
        run: |
          npm i --ignore-scripts
          npm run dist-win -- -p always --x64

  publish-win-arm64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-win-arm64' }}
    runs-on: windows-11-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup nodejs
        if: ${{ success() }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and publish
        if: ${{ success() }}
        run: |
          npm i --ignore-scripts
          npm run dist-win -- -p always --arm64 "-c.win.publish.provider=github" "-c.win.publish.publishAutoUpdate=false"

  publish-mac-universal:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-mac-universal' }}
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup nodejs
        if: ${{ success() }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and publish
        if: ${{ success() }}
        run: |
          npm i --ignore-scripts
          npm run dist-mac -- -p always --universal

  publish-appImage-x86_64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-appImage-x86_64' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup nodejs
        if: ${{ success() }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and publish
        if: ${{ success() }}
        shell: 'script -q -e -c "bash {0}"'
        run: |
          npm run docker-dist-appImage -- -- -p always --x64

  publish-appImage-arm64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-appImage-arm64' }}
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and publish
        run: |
          npm run docker-dist-appImage -- -- -p always --arm64

  publish-deb-amd64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-deb-amd64' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup nodejs
        if: ${{ success() }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and publish
        if: ${{ success() }}
        run: |
          sudo apt -y install ruby ruby-dev
          sudo gem install fpm -f
          npm i --ignore-scripts
          npm run dist-deb -- -p always --x64

  publish-deb-arm64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-deb-arm64' }}
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and publish
        run: |
          sudo apt update
          sudo apt -y install ruby ruby-dev
          sudo gem install fpm -f
          npm i --ignore-scripts
          npm run dist-deb -- -p always --arm64

  publish-rpm-x86_64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-rpm-x86_64' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup nodejs
        if: ${{ success() }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and publish
        if: ${{ success() }}
        run: |
          sudo apt -y install ruby ruby-dev rpm
          sudo gem install fpm -f
          npm i --ignore-scripts
          npm run dist-rpm -- -p always --x64

  publish-rpm-aarch64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-rpm-aarch64' }}
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build and publish
        run: |
          sudo apt update
          sudo apt -y install ruby ruby-dev rpm
          sudo gem install fpm -f
          npm i --ignore-scripts
          npm run dist-rpm -- -p always --arm64

  build-snap-amd64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'build-snap-amd64' || github.event.inputs.target_job == 'publish-snap' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build snap
        run: |
          sudo /sbin/iptables  -I DOCKER-USER -i lxdbr0 -j ACCEPT
          sudo /sbin/iptables  -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
          sudo apt update
          sudo snap install lxd
          sudo snap install --classic snapcraft
          sudo lxd init --auto
          npm run dist-snap -- --use-lxd

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-amd64
          path: dist/*.snap
          if-no-files-found: error

  build-snap-arm64:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'build-snap-arm64' || github.event.inputs.target_job == 'publish-snap' }}
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build snap
        run: |
          sudo apt update
          sudo snap install lxd
          sudo snap install --classic snapcraft
          sudo lxd init --auto
          npm run dist-snap -- --use-lxd

      - name: Upload snap artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-arm64
          path: dist/*.snap
          if-no-files-found: error

  publish-snap:
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.target_job == 'all' || github.event.inputs.target_job == 'publish-snap' }}
    runs-on: ubuntu-latest
    needs:
      - build-snap-amd64
      - build-snap-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download snap artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: snap-*
          path: dist
          merge-multiple: true

      - name: Push/release snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install --classic snapcraft
          find dist -name "*.snap" | xargs -I {} snapcraft upload {} --release beta
